### ISSUE TITLE
Add manage emails

### ISSUE THREAD

**Issue by Helghardt** [rehive/wallet-ionic#13]
1. Allow user to add and verify multiple emails.
2. Resend email verification.
3. Allow user to view and delete non-primary emails.
4. Remove email from user's emails if another user verifies the same email before it is verified.

**Comment by OdinsPlasmaRifle** [comment]
Steps 1-3 have been completed. In order to keep things simple: users cannot add email addresses/mobile numbers if someone has already claimed them regardless of whether they have verified the account. There are a lot of complications resulting in a system which not only allows multiple emails, but also allows unverified duplicates (eg. login after register cannot be allowed anymore [as an email might not be verified yet])

As a partial solution, we can perhaps add a script or task that clears out any unverified addresses after a certain amount of time passes? However, we will then have to decide what we do with primary addresses in these cases, not many clients will want the whole user deleted (for historic reasons) in these instances.
